### ISSUE TITLE
need help to get this running without a web server in Heroku

### ISSUE THREAD

**Issue by zs787** [heroku/heroku-buildpack-nginx#16]
Hi,

Would it be possible to know what changes I would need to make to deploy this as a standalone proxy app in Heroku, without the touch file step or any web-server. 

I would like to let it just listen to the Heroku $PORT env variable and then let my apps and incoming traffic proxy through it.

Would it just be the addition of a Procfile to start it ?

Thank you

**Comment by beanieboi** [comment]
hey,

you want to run nginx in what we call solo mode in this buildpack. there are some instructions in the README https://github.com/heroku/heroku-buildpack-nginx#requirements-solo-mode

ben
