### ISSUE TITLE
Failed to upgrade from cedar-14

### ISSUE THREAD

**Issue by e-coucou** [heroku/heroku-buildpack-nginx#33]
Hi,
I upgraded my old Cedar-14 to Heroku-18 and now my web app doesn't work any more.

the issue is : 
`2019-04-08T14:09:05.932714+00:00 app[web.1]: 2019/04/08 14:09:05 [crit] 17#0: *3 connect() to unix:/tmp/nginx.socket failed (2: No such file or directory) while connecting to upstream, client: xx.xx.xx.xx, server: _, request: "GET /index.html HTTP/1.1", upstream: "http://unix:/tmp/nginx.socket:/index.html"`

I add the Procfile with -> web: nginx-start-solo 

Does anyone could help me ?

Thanks
Eric

**Comment by beanieboi** [comment]
@e-coucou sorry we can't provide support here on GitHub. Would you mind opening a support ticket on Heroku.

Thank you

**Comment by mintotsai** [comment]
In case anyone runs into this issue and comes here, I was able to solve this by removing the "upstream app_server" in config/nginx.conf.erb.

`# upstream app_server {`
`#    server unix:/tmp/nginx.socket fail_timeout=0;`
`# }`

**Comment by beanieboi** [comment]
@mintotsai thanks for the added solution to the report.
would you mind adding a little more context here? Did you switch from the normal nginx to the nginx-solo-mode? The solo-mode default configuration does not include the upstream app_server.
i'm not sure how this is related to the cedar-14 to heroku-18 upgrade.
thanks for your input.

**Comment by SirMaster** [comment]
@e-coucou or @beanieboi what was the solution to this? I am having the same issue. Al though I started from a new version. It seems in the support ticket a solution was given. Any change you can share it here?
