### ISSUE TITLE
README nginx solo instructions

### ISSUE THREAD

**Issue by iqlinuxadmin** [heroku/heroku-buildpack-nginx#35]
I'm trying to configure nginx solo.  When I tried using the "Existing App Setup" example, it specified using heroku-community/nginx, but that doesn't contain bin/start-nginx-solo.

Now I'm using the New App example, which specifies
https://github.com/heroku/heroku-buildpack-nginx

and it's working.

**Comment by beanieboi** [comment]
Hey,

sorry for the confusion. i updated `heroku-community/nginx` and it should reflect was is in this repository right now. could you please try again

cheers

**Comment by iqlinuxadmin** [comment]
That worked!

Thanks for the quick response.

Cheers,
Sarah
