### ISSUE TITLE
HTTP/2 support ?

### ISSUE THREAD

**Issue by tmartres** [heroku/heroku-buildpack-nginx#50]
I couldn't find any information about implementing http 2 with this buildpack and I have tried to change my custom config files as per the normal Nginx documentation to no avail (my app just crashes). 

Any guides or pointers ?

**Comment by meltingice** [comment]
For what it's worth, Heroku doesn't support HTTP/2 yet, so adding it to nginx won't make any difference since the request still has to go through the Heroku router.

https://devcenter.heroku.com/articles/http-routing#http-versions-supported

**Comment by tmartres** [comment]
Can't believe it was written in the documentation all along.... Thanks for getting back on this !
