### ISSUE TITLE
Custom config is not working?

### ISSUE THREAD

**Issue by ivaaaan** [heroku/heroku-buildpack-nginx#64]
Hey. I've put `nginx.conf.erb` into `config/` directory of my app, and changed `location /` section to just `return`:

```
location / {
    return 200;
}
```

After deployment nothing changed, seems like buildpack ignores that file. Can you please suggest what's wrong, or how could I debug this? Build log says `nginx-buildpack: Custom config found in app/config.`

Procfile:
`web: bin/start-nginx nuxt start`

**Comment by hvitis** [comment]
+1 up

**Comment by hvitis** [comment]
Same here. I think I've spend like 5 hours trying to debug this half-blind. Any help much appreciated!

**Comment by hvitis** [comment]
I cant seem to trigger

`/tmp/app-initialized
`
In any possible way. 
My Procfile:

`web: bin/start-nginx nuxt start
`

My server/index.js

```
app.listen("/tmp/nginx.socket", () => {
    fs.openSync("/tmp/app-initialized", "w");
  });
```


My nginx.conf.erb
```

daemon off;
#Heroku dynos have at least 4 cores.
worker_processes <%= ENV['NGINX_WORKERS'] || 4 %>;

events {
	use epoll;
	accept_mutex on;
	worker_connections <%= ENV['NGINX_WORKER_CONNECTIONS'] || 1024 %>;
}
# From https://nuxtjs.org/faq/nginx-proxy/
map $sent_http_content_type $expires {
    "text/html"                 epoch;
    "text/html; charset=utf-8"  epoch;
    default                     off;
}

http {
        gzip on;
        gzip_comp_level 2;
        gzip_min_length 512;

	server_tokens off;

	log_format l2met 'measure#nginx.service=$request_time request_id=$http_x_request_id';
	access_log /dev/stdout;
	error_log /dev/stdout info;
	
	include mime.types;
	default_type application/octet-stream;
	sendfile on;

	#Must read the body in 5 seconds.
	client_body_timeout 5;

	# upstream app_server {
	# 	server localhost:<%= ENV["PORT"] %> fail_timeout=0;
	 # }
	upstream app_server {
		server unix:/tmp/nginx.socket fail_timeout=0;
 	}

	 server {
		listen <%= ENV["PORT"] %>;
		server_name _;
		keepalive_timeout 5;

		location = / {
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header Host $http_host;
			proxy_redirect off;
			proxy_pass http://127.0.0.1:3000;
		}
	}
}
```

**Comment by GarryGaller** [comment]
What port should I specify for my application? If you register your own, heroku says that it is busy.
Why is there no example without using unix socket?

**Comment by beanieboi** [comment]
> What port should I specify for my application? If you register your own, heroku says that it is busy.

You get a port from Heroku and it's in the `PORT` env variable. you need to bind to that one. The communication between your app and nginx is up to you, we suggest using a socket because it's only local communication.

**Comment by beanieboi** [comment]
> 			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> 			proxy_set_header Host $http_host;
> 			proxy_redirect off;
> 			proxy_pass http://127.0.0.1:3000;

It looks like you configured upstream on the socket but you are not using it. Is this intentional? Sorry I can't provide support for specific frameworks. If you are still stuck I suggest opening a support ticket

I just tested a nginx with a custom config file and it pick up my custom config.

**Comment by GarryGaller** [comment]
I try to run the app and get this:
2020-12-24T17:29:39.685491+00:00 app[web.1]: [martini] listening on :3000 (development)
2020-12-24T17:29:40.247563+00:00 app[web.1]: buildpack=nginx at=app-initialization
2020-12-24T17:29:41.248980+00:00 app[web.1]: buildpack=nginx at=app-initialization
....
2020-12-24T17:30:38.104040+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2020-12-24T17:30:38.125987+00:00 heroku[web.1]: Stopping process with SIGKILL
2020-12-24T17:30:38.213315+00:00 heroku[web.1]: Process exited with status 137
2020-12-24T17:30:38.253209+00:00 heroku[web.1]: State changed from starting to crashed


Congig nginx:

    upstream app_server {
        server localhost:<%= ENV['APP_PORT'] %> fail_timeout=0;
    }
    
    # --request routing--
    server {
        server_name  _;
        listen       <%= ENV['PORT'] %>;
        port_in_redirect off;   
        autoindex           off;
        
        root   /app/assets;
        
        location /api/v1.0/ {
            proxy_pass http://app_server;
            proxy_redirect off;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Real-IP $remote_addr;
    }


I don't understand what I'm doing wrong....

**Comment by beanieboi** [comment]
You need to touch `/tmp/app-initialized` to tell nginx that your application is ready to receive requests.
See https://github.com/heroku/heroku-buildpack-nginx#requirements-proxy-mode and https://github.com/heroku/heroku-buildpack-nginx/blob/master/bin/start-nginx#L41-L53

**Comment by GarryGaller** [comment]
**beanieboi**, Oh I did: I entered the touch /tmp/app-initialized command in bush

**Comment by beanieboi** [comment]
@GarryGaller How did you do that?

**Comment by GarryGaller** [comment]
**beanieboi**, I didn't understand your question. I wrote that I entered the command manually in the bash console on heroku.

**Comment by beanieboi** [comment]
@GarryGaller dynos are ephemeral. using `heroku run bash` will not get you onto the web dynos. you are running bash in a separate container. therefor touching `/tmp/app-initialized` is not visible to the web dynos. you need to create that file within your web process.

**Comment by GarryGaller** [comment]
**@beanieboi**, Thanks. I now realized what I was doing wrong.

**Comment by senolatac** [comment]
Followed this [example](https://github.com/rsgilbert/hellonuxt) but no chance. It says `buildpack=nginx at=app-initialization` on the logs. Any suggestion here?
