### ISSUE TITLE
Update readme/config with ssl redirect example

### ISSUE THREAD

**Issue by niedfelj** [heroku/heroku-buildpack-nginx#66]
Hi,

Could you update the readme/config with a sample to force SSL? I think it would be useful as Heroku is a bit non-standard in this regard. I believe this is the config:

if ($http_x_forwarded_proto != "https") {
  return 301 https://$host$request_uri;
}

**Comment by beanieboi** [comment]
@niedfelj sorry, i'm pretty busy at the moment. would you be able to open a PR for that? i'd really appreciate that.

**Comment by niedfelj** [comment]
@beanieboi here https://github.com/heroku/heroku-buildpack-nginx/pull/68
