### ISSUE TITLE
Add Google PageSpeed support conditionally

### ISSUE THREAD

**Issue by harrylewis** [heroku/heroku-buildpack-nginx#73]
Hi there 👋 

My company has been using Heroku and NGINX for a long time now. We currently use a custom buildpack that builds NGINX and configures it with the Google PageSpeed module added in.

I wanted to see if there was any interest in offering support for including the Google PageSpeed module in the community buildpack. This would allow my company and others to have easy access to this module with the community version.

I could see this being implemented in one of two ways.

The first way could be to create additional build targets in the `Makefile` for NGINX with PageSpeed, and then commit the resulting packaged binaries: `nginx-with-pagespeed-heroku-16.tgz`, etc. Bringing PageSpeed into the Heroku application during the build in that case could involve setting some sort of environment variable `NGINX_WITH_PAGESPEED=true` to dynamically include it. Of course, the conversation becomes, do we then need to accommodate new binaries for all add-on modules? I'd argue since this is a more popular one, that maybe only PageSpeed would be supported.

The second way could be to just include Google PageSpeed in the factory build of NGINX. I'm not totally sure of the downstream implications of this. I imagine that could result in a larger binary, and possibly a larger Heroku slug, which may not be ideal.

Anyways, I'm curious to hear your thoughts about this! If there is interest, I would love to create a PR for it.

**Comment by beanieboi** [comment]
Hi 👋🏼 

thanks for the proposal. I'd like to keep the maintenance efforts to a minimum. This buildpack is maintained in my spare time and not in an official capacity from Heroku. The main driver behind this buildpack is our own need for it. I'd like to not add feature that we don't use internally but add a maintenance burden. For us it's totally acceptable and we encourage people to fork the buildpack if they have special requirements. 

I hope you understand this.
Thank you
Ben

**Comment by harrylewis** [comment]
Hey @beanieboi thanks for the response. I definitely understand your concern here with increasing maintenance load. Thanks for the explanation. We will continue along with our own fork!
